spring:
  jpa: # jpa配置
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.format_sql: false
    database: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/three_system?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    druid:
      initial-size: 5 # 初始化连接大小
      minIdle: 5     # 最小连接池数量
      maxActive: 20  # 最大连接池数量
      maxWait: 60000 # 获取连接时最大等待时间，单位毫秒
      timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000   # 配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 from DUAL  # 测试连接
      testWhileIdle: true                  # 申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      testOnBorrow: false                  # 获取连接时执行检测，建议关闭，影响性能
      testOnReturn: false                  # 归还连接时执行检测，建议关闭，影响性能
      poolPreparedStatements: false        # 是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      maxPoolPreparedStatementPerConnectionSize: 20 # 开启poolPreparedStatements后生效
      filters: stat,wall # 配置扩展插件，常用的插件有=>stat:监控统计 wall:防御sql注入
      connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000' # 通过connectProperties属性来打开mergeSql功能;慢SQL记录
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: cloud-dev
    password: cloud-dev
    virtual-host: /
  #  redis:
  #    host: localhost
  #    port: 6379
  #    password:
  #    timeout: 10s
  #    lettuce:
  #      pool:
  #        min-idle: 0
  #        max-idle: 8
  #        max-active: 8
  #        max-wait: -1ms
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    proxy-target-class: true
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sender:
      type: web
logging:
  level:
    root: info
    com.three: debug
    org.springframework.security: debug
  file: logs/${spring.application.name}.log
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8084/three-auth-server/user-me
      prefer-token-info: false
#wechat:
#  domain: http://api.gateway.com:8080/api-u
#  infos:
#    app1:
#      appid: xxx
#      secret: xxx
#    app2:
#      appid: xxx
#      secret: xxx
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000